### ISSUE TITLE
How to pair new MAX! devices

### ISSUE THREAD

**Issue by ersterexitus** [powerpaul17/maxcul#5]
Hello,

i install your integration, but no pairing is working for me.
I start the service "Max CUL: enable_pairing" and set the device path to "192.168.x.x:2323"
But nothing happened. In the Logs the pairing request is shown:
2023-06-20 21:52:45.412 INFO (Thread-3) [maxcul._communication] Pairing requested but pairing disabled, not pairing to new device

how to pair the devices correctly?

Thanks

**Comment by powerpaul17** [comment]
I think you might have to prefix the device path with `telnet://`, can you try that please?

**Comment by ersterexitus** [comment]
that worked and the pairing is successfully. Many thanks, one step closer to migrate from fhem to home assistant
Are there any plans for further extensions like set boostduration, vavleoffset , weekprofil and so on? I came from them where such features are available

**Comment by powerpaul17** [comment]
Sorry, I don't have plans for this since the thermostats and the cube are really old (and not very secure). I just created this extension to extend their lifespan in my home a bit longer but since I'm basically controlling the schedule with HA (I have the thermostats in manual mode) I don't see any benefit in programming it into them.

**Comment by ersterexitus** [comment]
Thanks for your reply.
